# Generated by Django 4.2.3 on 2023-07-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fulfillment_status',
        ),
        migrations.AddField(
            model_name='order',
            name='fulfilment_status',
            field=models.CharField(default='Pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=128),
        ),
    ]
