# Generated by Django 4.2.3 on 2023-07-12 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_order_fulfillment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fulfilment_status',
            new_name='fulfillment_status',
        ),
    ]
