# Generated by Django 4.2.3 on 2023-07-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_razorpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(default='Processing', max_length=128),
        ),
    ]
