# Generated by Django 4.2.3 on 2023-07-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_couponhistory_used_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='couponhistory_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
