# Generated by Django 4.2.3 on 2023-07-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_coupon_minimum_purchase_couponhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
