# Generated by Django 4.2.3 on 2023-07-24 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_alter_productvariant_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CouponHistory',
        ),
    ]
