# Generated by Django 4.2.3 on 2023-07-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to='category_images/'),
        ),
    ]
