# Generated by Django 4.2.3 on 2023-07-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_address_addressee_defaultaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressee',
            field=models.CharField(default='', max_length=100),
        ),
    ]
