# Generated by Django 4.2.3 on 2023-07-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_userprofile_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultAddress',
        ),
    ]
