# Generated by Django 4.2.3 on 2023-07-11 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_defaultaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultAddress',
        ),
    ]
