# Generated by Django 4.2.3 on 2023-07-11 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_delete_defaultaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAddress',
            fields=[
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='userprofile.userprofile')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.address')),
            ],
        ),
    ]
